---
title: "Group assignment of Week5"
author: "group 6: Finn Womack, Lorne Curran, Martin Leandro Uranga Priore, Chenyang Duo, Emerson Webb, Jiarui Xu"
date: "5/2/2019"
output: pdf_document
---

```{r, include=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      fig.show = "hold")
library(tidyverse)
library(ggrepel)
rm(list = ls())
```

## Plot1

```{r}
tax <- tribble(
  ~ Country,     ~ `1970`, ~ `1979`,
  "Sweden",          46.9,     57.4,
  "Netherlands",     44.0,     55.8,
  "Norway",          43.5,     52.2,
  "Britain",         40.7,     39.0,
  "France",          39.0,     43.4,
  "Germany",         37.5,     42.9,
  "Belgium",         35.2,     43.2,
  "Canada",          34.9,     35.8,
  "Finland",         34.9,     38.2,
  "Italy",           30.4,     35.7,
  "United States",   30.3,     32.5,
  "Greece",          26.8,     30.6,
  "Switzerland",     26.5,     33.2,
  "Spain",           22.5,     27.1,
  "Japan",           20.7,     26.6
)

tidytax <- tax %>% 
  gather(`1970`, `1979`, key = "year", value = "GDP", convert = T)
```

```{r, eval = FALSE, include=FALSE}
# earlier version not run

ggplot(tidytax)+
  geom_line(aes(x = year, y = GDP, group = Country), size = .3)+
  theme_void()+
  xlab("")+
  ylab("")+
  scale_y_continuous(limits = c(20, 63))+
  scale_x_continuous(limits = c(1963, 1980))+
  geom_text_repel(data = filter(tidytax, year == 1970), 
                  aes(x = year, y = GDP, label = Country),
                  nudge_x = -1, hjust = 1, direction = "y", size = 2.5)+
  geom_text_repel(data = filter(tidytax, year == 1970), 
                  aes(x = year, y = GDP, label = GDP), 
                  direction = "y", nudge_x=-.2,size = 2.5)+
  geom_text_repel(data = filter(tidytax, year == 1979), 
                  aes(x = year, y = GDP, label = Country), 
                  direction = "y", size = 2.5, 
                  nudge_x = 0.25, hjust = -0.5)+
  geom_text_repel(data = filter(tidytax, year == 1979), 
                  aes(x = year, y = GDP, label = GDP),
                  direction = "y", size = 2.5)+
  annotate("text", x = c(1970, 1979), y = 60, 
           label = c("1970", "1979"))+
  annotate("text", x = 1965, y = 58, label = 
             paste("Current Receipts of Government as a\n", 
            "Percentage of Gross Domestic\nProduct, 1970 and 1979"))
```



```{r}
ggplot(tidytax)+
  geom_line(aes(x = year, y = GDP, group = Country), size = .3)+
  theme_void()+
  xlab("")+
  ylab("")+
  scale_y_continuous(limits = c(20, 63))+
  scale_x_continuous(limits = c(1963, 1980))+
  geom_text(data = filter(tidytax, year == 1970),
                  aes(x = year, y = GDP, label = Country),
                  nudge_x = -1, hjust = 1, size = 2.5)+
  geom_text_repel(data = filter(tidytax, year == 1970), 
                  aes(x = year, y = GDP, label = GDP), 
                  direction = "y", nudge_x=-.2,size = 2.5)+
  geom_text(data = filter(tidytax, year == 1979), 
                  aes(x = year, y = GDP, label = Country), size = 2.5,
                  nudge_x = 0.25, hjust = -0.5)+
  geom_text_repel(data = filter(tidytax, year == 1979), 
                  aes(x = year, y = GDP, label = GDP),
                  direction = "y", size = 2.5)+
  annotate("text", x = c(1970, 1979), y = 60, 
           label = c("1970", "1979"))+
  annotate("text", x = 1965, y = 58, 
    label = "Current Receipts of Government\n as Percentage of Gross Domestic\n Product, 1970 and 1979", 
    size = 2.5)

```

## Plot2

```{r}
volcano_tbl <- as_tibble(volcano)
colnames(volcano_tbl) <- 1:ncol(volcano) 
volcano_tbl$row <- 1:nrow(volcano_tbl)

volcano_tbl_new <- gather(volcano_tbl,variable,topology,-row,convert = TRUE)
ggplot(volcano_tbl_new, aes(x=row, y=variable,z=topology,fill=topology))  + 
  geom_tile() + 
  coord_equal() +
  geom_contour(color = "white", alpha = 0.5) + 
  scale_fill_distiller(palette="Spectral", na.value="white") + 
  theme_bw() +
  labs(title = "Maunga Whau Topology")
```

## Plot3

```{r, eval=FALSE, echo=FALSE}

# earlier version not run
budget <- tribble(
  ~ Expenses,             ~ Jan, ~ Feb, ~ Mar, ~ Apr, ~ May, ~ Jun, ~ Jul, ~ Aug, ~ Sep, ~ Oct, ~ Nov, ~ Dec,
  "Domestic Actual",      84853, 84838, 88103, 85072, 88723, 90384, 89374, 95273, 94239, 92394, 96934, 105034,
  "Domestic Budget",      83000, 83830, 84668, 85515, 86370, 87234, 88106, 88987, 89877, 90776, 91684, 92600,
  "International Actual", 12538, 12438, 14934, 14033, 13945, 15938, 14086, 15934, 13945, 17338, 19384, 22394,
  "International Budget", 12000, 12600, 13860, 13200, 13860, 15246, 14520, 15246, 16771, 15972, 16771, 18448
)
budget_new<- gather(budget,variable,value,-Expenses)

a<- subset(budget_new,Expenses=="Domestic Actual")$value
b<-subset(budget_new,Expenses=="Domestic Budget")$value
c<- subset(budget_new,Expenses=="International Actual")$value
d<- subset(budget_new,Expenses=="International Budget")$value
Domestic_difference <- a-b
International_difference <- c-d
Domestic_proportion <- (a-b)/a
International_proportion <- (c-d)/c
Month<- factor(subset(budget_new,Expenses=="Domestic Actual")$variable,levels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))

budget_diff <- data.frame(Domestic_difference,International_difference,Domestic_proportion,International_proportion,Month)
budget_diff_new<- gather(budget_diff[c(1,2,5)],key="Type",value = "Difference",Domestic_difference,International_difference,-Month)
budget_diff_new<- as_tibble(budget_diff_new)
ggplot(budget_diff_new,aes(x=Month,y=Difference,group=Type,colour=Type))+
  geom_line()+
  geom_point()+ylab("")+xlab("")+labs(title = "Expense Variance from Budget in U.S. Dollars")

budget_diff_new2<- gather(budget_diff[c(3,4,5)],key="Type",value = "Difference",Domestic_proportion,International_proportion,-Month)
budget_diff_new2<- as_tibble(budget_diff_new2)
ggplot(budget_diff_new2,aes(x=Month,y=Difference,group=Type,colour=Type))+
  geom_line()+
  geom_point()+ylab("")+xlab("")+labs(title = "Percentage Variance of Expenses from Budget")
```


```{r, out.width="50%"}
budget <- tribble(
  ~ Expenses,             ~ Jan, ~ Feb, ~ Mar, ~ Apr, ~ May, ~ Jun, ~ Jul, ~ Aug, ~ Sep, ~ Oct, ~ Nov, ~ Dec,
  "Domestic Actual",      84853, 84838, 88103, 85072, 88723, 90384, 89374, 95273, 94239, 92394, 96934, 105034,
  "Domestic Budget",      83000, 83830, 84668, 85515, 86370, 87234, 88106, 88987, 89877, 90776, 91684, 92600,
  "International Actual", 12538, 12438, 14934, 14033, 13945, 15938, 14086, 15934, 13945, 17338, 19384, 22394,
  "International Budget", 12000, 12600, 13860, 13200, 13860, 15246, 14520, 15246, 16771, 15972, 16771, 18448
)

budget_new <- gather(budget,variable,value,-Expenses)

a <- subset(budget_new,Expenses=="Domestic Actual")$value
b <- subset(budget_new,Expenses=="Domestic Budget")$value
c <- subset(budget_new,Expenses=="International Actual")$value
d <- subset(budget_new,Expenses=="International Budget")$value

Domestic_difference <- a-b
International_difference <- c-d
Domestic_proportion <- (a-b)/a
International_proportion <- (c-d)/c
Month <- factor(subset(budget_new, Expenses=="Domestic Actual")$variable, levels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep",
                                                "Oct","Nov","Dec"))

budget_diff <- tibble(Domestic_difference,International_difference,
                      Domestic_proportion,International_proportion,Month)
budget_diff_new<- gather(budget_diff[c(1,2,5)],key="Type",
                         value="Difference",Domestic_difference,
                         International_difference,-Month)

ggplot(budget_diff_new,aes(x=Month,y=Difference,group=Type,colour=Type))+
  geom_line()+
  geom_point()+ylab("")+xlab("")+
  labs(title = "Expense Variance from Budget in U.S. Dollars")

budget_diff2 <- gather(budget_diff[c(3,4,5)],key="Type",
                       value="Difference",Domestic_proportion,
                                 International_proportion,-Month)

ggplot(budget_diff2,aes(x=Month,y=Difference,group=Type,colour=Type))+
  geom_line()+
  geom_point()+ylab("")+xlab("")+
  labs(title = "Percentage Variance of Expenses from Budget")

```
