---
title: "Revealing change: housing sales"
author: "group 6: Finn Womack, Lorne Curran, Martin Leandro Uranga Priore, Chenyang Duo, Emerson Webb, Jiarui Xu"
date: "5/10/2019"
output: pdf_document
---
  
```{r, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, 
                      fig.show = "hold")
library(tidyverse)
library(readxl)
library(gridExtra)
library(scales)
rm(list = ls())
```


```{r}
# Get data  -------------------------------------------
# Data comes from https://www.census.gov/construction/nrs/historical_data/index.html
# Right clicking on "Houses Sold by Sales Price: U.S. Total (2002-present)" XLS
# link, gives the following url and file name.
file_name <- "usregsoldbyprice_cust.xls"
url <- "https://www.census.gov/construction/nrs/xls/"
# only download if it isn't already here
if(!file.exists(file_name)){
  download.file(paste0(url, file_name), file_name, mode = "wb")
}
# Read data:
housesold <- read_excel(file_name,
                        col_names = c("Period", "Total", "Below 125k", 
                                      "125-150k","150-199k",
                                      "200-$250k","250-299k",
                                      "300-$400k","400-500k",
                                      "500-$750k","750k+"),
                        skip = 8)
# Tidying data:
# /Gathering subtotals and set order:
housesold <- housesold %>% gather("Below 125k","125-150k","150-199k",
                                      "200-$250k","250-299k",
                                      "300-$400k","400-500k",
                                      "500-$750k","750k+", key = "level", value = "Sub_Total")
housesold$level <- factor(housesold$level, 
  levels = c("Below 125k", "125-150k","150-199k","200-$250k",
             "250-299k","300-$400k","400-500k","500-$750k","750k+"))
# /Select 02-13 and Calculate percentages
housesold <- housesold %>% 
  filter(Period > 2001 & Period<2014) %>%
  mutate(Pct = 100*Sub_Total/Total)
# /Calculate difference with 2006-2008 average
avr0208 <- housesold %>% 
  filter(Period > 2005 & Period<2009) %>%
  group_by(level) %>%
  summarise(avr0208 = mean(Sub_Total, na.rm = TRUE))
housesold <- housesold %>% right_join(avr0208, by = c('level'='level'))
# /Calculate difference with 2002
Sub_Total02<- housesold %>% 
  filter(Period == 2002) %>%
  select(level, Sub_Total02 = Sub_Total)
housesold <- housesold %>% right_join(Sub_Total02, by = c('level'='level'))


```

Fig. 8.15
```{r, out.width = "1000px"}

# Plots:
# /8.15
# //Top
labelpts_df <- data.frame(x = c(2002,2005,2013), 
           y = c(973, 1283, 429), 
           labs = c("973", "1283", "429"))
fif_top <- housesold %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = Total))+
  labs(title = "Single-Family Housees sold", 
       subtitle = "Thousands of units sold")+
  theme_classic()+
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(),
        plot.title = element_text(size = 8),
        plot.subtitle = element_text(size = 7))+
  scale_x_continuous(breaks = c(2002,2004,2006,2008,2010,2012,2013))+
  scale_y_continuous(breaks = c(0, 500, 1000, 1300))+
  geom_point(data = labelpts_df, aes(x = x, y = y))+
  geom_text(data = labelpts_df, 
            aes(x = x, y = y, label = labs), 
            nudge_y = 85, size = 2)
  
  
  
# //Mid
fif_mid <- housesold %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = Sub_Total))+
  scale_x_continuous(breaks = c(2002, 2013))+
  theme_classic()+
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_wrap(~level, nrow = 1)+
  labs(title = "By price range",
       subtitle = "Thousands of Units sold")+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8),
        plot.title = element_text(size = 8),
        plot.subtitle = element_text(size = 7))
  

# //Bottom
fif_bot <- housesold %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = Pct))+
  scale_x_continuous(breaks = c(2002, 2013))+
  scale_y_continuous(breaks = c(0,10,20,30))+
  theme_classic()+
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_wrap(~level, nrow = 1)+
  labs(subtitle = "As a percentage of all single-family houses sold")+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 7),
        plot.subtitle = element_text(size = 8))
grid.arrange(fif_top,fif_mid,fif_bot, nrow = 3)

```

\pagebreak

Fig. 8.16
```{r}

# /8.16
# //Top
six_top <- housesold %>% mutate(diff = 100*(Sub_Total - avr0208)/avr0208) %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = diff)) +
  geom_hline(yintercept = 0, linetype="dotted") +
  geom_vline(xintercept = 2001, linetype="dotted")+
  scale_x_continuous(breaks = c(2002, 2013))+
  scale_y_continuous(breaks = c(-100, 0, 100, 150), 
                     labels = c("-100%", "0%", "100%", "150%"),
                     limits = c(-100,150))+
  theme_classic()+
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_wrap(~level, nrow = 1)+
  labs(subtitle = "In comparison to the 2006-2008 average (0% point)")+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 7))

# //Bottom
six_bot <- housesold %>% mutate(diff = 100*(Sub_Total - Sub_Total02)/Sub_Total02) %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = diff)) +
  geom_hline(yintercept = 0, linetype="dotted") +
  geom_vline(xintercept = 2001, linetype="dotted")+
  scale_x_continuous(breaks = c(2002, 2013))+
  scale_y_continuous(breaks = c(-100, 0, 100, 200, 300), 
                     labels = c("-100%", "0%", "100%", "200%", "300%"),
                     limits = c(-110, 310))+
  theme_classic()+
  theme(axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(), 
        axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_wrap(~level, nrow = 1)+
  labs(subtitle = "In comparison to 2002 (0% point)")+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 7))

grid.arrange(six_top, six_bot, nrow = 2)

```

\pagebreak

Fig. 8.17
```{r}

# /8.17
# //Left
sev_left <- housesold %>% mutate(diff = 100*(Sub_Total - avr0208)/avr0208) %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = diff, color = level)) +
  geom_hline(yintercept = 0, linetype = "dotted")+
  labs(title = "In comparison to the 2006-2008 average (0% point)")+
  scale_x_continuous(breaks = 2002:2013,
                     labels = c("2002", rep("", 10), "2013"))+
  scale_y_continuous(breaks = c(-100, 0, 100, 150),
                     labels = c("-100%", "0%", "100%", "150%"),
                     limits = c(-100, 300))+
  theme_classic()+
  theme(legend.position="none", 
        axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(),
        plot.title = element_text(size = 8))

# //Right
sev_right <- housesold %>% mutate(diff = 100*(Sub_Total - Sub_Total02)/Sub_Total02) %>%
  ggplot() +
  geom_line(mapping = aes(x = Period, y = diff, color = level)) +
  geom_hline(yintercept = 0, linetype = "dotted")+
  labs(title = "In comparison to 2002 (0% point)")+
  scale_x_continuous(breaks = 2002:2013,
                     labels = c("2002", rep("", 10), "2013"))+
  scale_y_continuous(breaks = c(-100, 0, 100, 200, 300),
                     labels = c("-100%", "0%", "100%", "200%", "300%"),
                     limits = c(-100, 300))+
  theme_classic()+
  theme(legend.position="none", 
        axis.line = element_blank(),
        axis.title.x = element_blank(),
          axis.title.y = element_blank(),
        plot.title = element_text(size = 8))

grid.arrange(sev_left, sev_right, ncol = 2)

```

