---
title: "Construct Exploration"
author: "Group 6"
date: "April 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, results='hide'}
library(tidyverse)
```

```{r, message=FALSE}
library(babynames)
alt_graph <- ggplot(filter(babynames, name == "Finn"), aes(year, n)) +
  #geom_line(aes(y=max, colour="red"), size=1) +
  #geom_line(aes(y=min, colour=sblue), size=1) +
  #geom_ribbon(aes(ymin=min,ymax=max), fill="grey", alpha="0.5") +
  geom_smooth(color = "purple", size=1, se=FALSE) +
  geom_smooth(data=filter(babynames, name == "Martin"),color = "green", size=1, se=FALSE ) +
  geom_smooth(data=filter(babynames, name == "Lorne"),color = "blue", size=1, se=FALSE ) +
  geom_smooth(data=filter(babynames, name == "Chenyang"),color = "red", size=1, se=FALSE ) +
  geom_smooth(data=filter(babynames, name == "Emerson"),color = "orange", size=1, se=FALSE ) +
  geom_smooth(data=filter(babynames, name == "Sam"),color = "yellow2", size=1, se=FALSE ) +
  #scale_color_manual(name="" ,values= c("blue", "red", "yellow2", "red", "green", "purple"), labels = c("Lorne", "Chenyang", "Sam", "Emerson", "Martin", "Finn")) +
  labs(x = "Year", y = "Proportion") +
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13)) +
  theme_bw()

alt_graph

```

```{r}
sblue = rgb(8/256,30/256,66/256)
# She said non-standard statistics so I made my own name diversity measure that is the inverse of the maximum proportion i.e. goes up the lower the proportion of the most used name is
babynames %>%
  group_by(year) %>%
  summarize(name_diversity_index = 1/max(prop)) %>%
  ggplot(aes(year, name_diversity_index)) +
  geom_line(color = sblue) +
  labs(x = "Year", y = "Name Diversity Index") +
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13))
        
```

```
#Also tried out inverse median and number of unique names
babynames %>%
  group_by(year) %>%
  summarize(name_diversity_index = 1/median(prop)) %>%
  ggplot(aes(year, name_diversity_index)) +
  geom_line(color = sblue) +
  labs(x = "Year", y = "Name Diversity Index") +
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13))

babynames %>%
  group_by(year) %>%
  summarize(unique_names = length(unique(name))) %>%
  ggplot(aes(year, unique_names)) +
  geom_line(color = sblue) +
  labs(x = "Year", y = "Unique Names") +
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13))

```

```{r}
# Tried plotting the peak popularity of names for each year
babynames %>%
  group_by(name) %>%
  summarise(peak_year=year[which.max(prop)]) %>%
  ggplot(aes(peak_year)) + geom_bar(colour = rainbow(138)) +
  labs(x = "Year", y = "n names w/ peak popularity") +
  theme(axis.title.x = element_text(size = 13), 
        axis.title.y = element_text(size = 13))
  
```

